// Copyright © 2015 Lower Columbia College Computer Science Club

// This file is part of Barcode Clocking.

// Barcode Clocking is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Barcode Clocking is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with Barcode Clocking.  If not, see <http://www.gnu.org/licenses/>.

// If you have any questions or comments, please contact the current Club
// President or Club Vice President.

// NOTE: BarcodeClocking (BC) depends on the exe that is generated by
// MorseCodeListener (MCL). It's included as a Resource. This solution is
// configured to build MCL before building BC. The pre-build event command line
// for BC has a command to copy the MCL exe of the same build configuration (as
// set for BC at that time) to the Resources directory of BC. It is therefore
// important to keep the build configuration for both projects the same.

using STA.Settings;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Windows.Forms;

namespace BarcodeClocking
{
    public partial class FormMain : Form
    {
        #region Declarations

        // vars
        private bool closing = false;
        private bool opening = true;
        private bool selfChanged = false;
        private char[] invalidChars;
        private INIFile settingsFile;
        private List<Card> cardList;
        private Process morseCodeListener;
        private string input;

        #endregion

        #region General Form Stuff

        public FormMain()
        {
            // vars
            bool goAgain;

            // get list of invalid chars for system
            invalidChars = Path.GetInvalidFileNameChars();

            // check for existence of required iText DLL
            if (!File.Exists("itextsharp.dll"))
            {
                do
                {
                    // (re)set vars
                    goAgain = false;

                    try
                    {
                        // extract file
                        File.WriteAllBytes("itextsharp.dll", Properties.Resources.itextsharp);
                    }
                    catch (Exception err)
                    {
                        // ask user what they want to do
                        switch (MessageBox.Show(this, "There was an error while trying to extract the required file for generating the time sheet.\n\n" + err.Message + "\n\nAbort will close this application. Ignore will temporarily disable the option to make the time sheets.", "Extract File Error", MessageBoxButtons.AbortRetryIgnore, MessageBoxIcon.Error))
                        {
                            // exit the app
                            case DialogResult.Abort: this.Close();
                                break;
                            // try extracting the file again
                            case DialogResult.Retry: goAgain = true;
                                break;
                            // disable option to generate time sheets and add the reason why
                            case DialogResult.Ignore: ToolStripMenuItemGenerate.Enabled = false;
                                ToolStripMenuItemGenerate.ToolTipText = "The required file isn't available.";
                                break;
                        }
                    }
                } while (goAgain);
            }

            // create gui
            InitializeComponent();

            //Start the clock
            //System.Windows.Forms.Timer clockTimer = new System.Windows.Forms.Timer();


            // load list of cards
            LoadCards();


            // prepare settings
            settingsFile = new INIFile("BarcodeClocking.ini", false, true);

        }

        private void LoadCards()
        {
            try
            {
                // create vars
                cardList = new List<Card>();
                if (!File.Exists("cardList.txt"))
                    File.AppendAllText("cardList.txt", "");
                string[] tempList = File.ReadAllLines("cardList.txt");

                // go through each line from file
                foreach (string card in tempList)
                {
                    // vars
                    bool isClocked;

                    // split line into parts
                    string[] cardParts = card.Split(new char[] { '\t' });

                    // see if this card hasn't clocked out
                    if (File.Exists(cardParts[0] + ".txt"))
                    {
                        string[] records = File.ReadAllLines(cardParts[0] + ".txt");
                        if (records[records.Length - 1].EndsWith("\t"))
                            isClocked = true;
                        else
                            isClocked = false;
                    }
                    else
                        isClocked = false;

                    // add card to list
                    cardList.Add(new Card(cardParts[0], cardParts[1], isClocked));
                }
            }
            catch (Exception err)
            {
                MessageBox.Show(this, "There was an error while loading the list of cards.\n\n" + err.Message, "Card Load Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

            // check for empty card list
            if (cardList.Count == 0)
                MessageBox.Show(this, "It looks like there aren't any registered cards yet. You can add a card by pressing Alt + N on the keyboard, or by clicking on the 'Add new card' option from the 'Manage Cards' menu.", "No Registered Cards", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
        }

        private void FormMain_Deactivate(object sender, EventArgs e)
        {
            // try to keep this form activated to capture input
            Thread.Sleep(500);
            this.Activate();
        }

        private void TimerInputTimeout_Tick(object sender, EventArgs e)
        {
            // reset input storage
            LabelInput.Text = "input: ";
            input = "";

            // reset status indicator
            ResetStatus();

            // disable timer
            TimerInputTimeout.Enabled = false;
        }

        private void StoreInput(char inputChar)
        {
            // make sure no dialogs from this app are open
            if (!(this.Visible && !this.CanFocus))
            {
                // make sure this is thread-safe
                if (LabelInput.InvokeRequired)
                    this.Invoke(new MethodInvoker(delegate() { StoreInput(inputChar); }));
                else
                {
                    // work with backspace
                    if (inputChar.Equals('\b'))
                    {
                        // make sure there's at least one char to remove
                        if (input.Length > 0)
                        {
                            LabelInput.Text = LabelInput.Text.Substring(0, LabelInput.Text.Length - 1);
                            input = input.Substring(0, input.Length - 1);
                        }

                        // reset timer
                        TimerInputTimeout.Stop();
                        TimerInputTimeout.Interval = 5000;
                        TimerInputTimeout.Start();

                        // stop processing input
                        return;
                    }
                    // replace invalid chars
                    else if (invalidChars.Contains(inputChar))
                        inputChar = '_';

                    // store input
                    LabelInput.Text = LabelInput.Text + inputChar.ToString();
                    input = input + inputChar.ToString();

                    // reset timer
                    TimerInputTimeout.Stop();
                    TimerInputTimeout.Interval = 5000;
                    TimerInputTimeout.Start();
                }
            }
        }

        private void ResetStatus()
        {
            LabelStatus.Text = "Waiting for card scan . . .";
        }

        #endregion

        #region Time Calculation Stuff

        private void FormMain_KeyPress(object sender, KeyPressEventArgs e)
        {
            // vars
            bool inList = false;
            DateTime clockedIn;
            DateTime clockedOut;

            // check for user/scanner pressing enter
            if (e.KeyChar.Equals('\r') || e.KeyChar.Equals('\n'))
            {
                // remove leading and trailing spaces
                input = input.Trim();

                // check for existence of card
                for (int i = 0; i < cardList.Count; i++)
                {
                    if (cardList[i].cardID == input)
                    {
                        // flag it
                        inList = true;

                        // check for clock-in or -out
                        if (cardList[i].clockedIn)
                        {
                            try
                            {
                                // clock out
                                cardList[i].clockedIn = false;
                                File.AppendAllText(input + ".txt", DateTime.Now.ToString() + "\r\n");
                            }
                            catch (Exception err)
                            {
                                MessageBox.Show(this, "There was an error while trying to clock you out.\n\n" + err.Message, "Clock Out Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }

                            // calculate time logged
                            TimeSpan diff = new TimeSpan(0, 0, 0, 0);
                            try
                            {
                                string[] records = File.ReadAllLines(input + ".txt");
                                string[] temp = records[records.Length - 1].Split(new char[] { '\t' });
                                clockedIn = DateTime.Parse(temp[0]);
                                clockedOut = DateTime.Parse(temp[1]);
                                diff = clockedOut - clockedIn;
                            }
                            catch (Exception err)
                            {
                                MessageBox.Show(this, "There was an error while trying to calculate the time you clocked.\nWas someone playing with the database files?\n\n" + err.Message, "Clocked Time Calculation Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }

                            // show confirmation
                            LabelStatus.Text = "Goodbye " + cardList[i].fName + ".\nYou logged " + GenerateClockedTime(diff) + ".";
                            TimerInputTimeout.Interval = 3000;
                            TimerInputTimeout.Enabled = true;
                        }
                        else
                        {
                            // clock in
                            cardList[i].clockedIn = true;
                            try
                            {
                                File.AppendAllText(input + ".txt", DateTime.Now.ToString() + "\t");
                            }
                            catch (Exception err)
                            {
                                MessageBox.Show(this, "There was an error while trying to clock you in.\n\n" + err.Message, "Clock In Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }

                            // show confirmation
                            LabelStatus.Text = "Hello " + cardList[i].fName + "!\nYou're now clocked in.";
                            TimerInputTimeout.Interval = 2500;
                            TimerInputTimeout.Enabled = true;
                        }

                        // stop processing the list
                        break;
                    }
                    

                    // check for unrecognized card
                    if (!inList)
                    {
                        // notify user of unrecognized card
                        LabelStatus.Text = "Unrecognized card!";
                        TimerInputTimeout.Interval = 2500;
                        TimerInputTimeout.Enabled = true;
                    }

                    // reset input storage
                    LabelInput.Text = "input: ";
                    input = "";
                }
            }
            else
                // add the input
                StoreInput(e.KeyChar);
        }

        private string GenerateClockedTime(TimeSpan diff)
        {
            // vars
            bool days = false;
            bool hours = false;
            bool minutes = false;
            bool seconds = false;
            string loggedTime = "";

            // figure out what to display
            if (diff.Days > 0)
                days = true;
            if (diff.Hours > 0)
                hours = true;
            if (diff.Minutes > 0)
                minutes = true;
            if (diff.Seconds > 0)
                seconds = true;

            // create logged time text
            if (days)
            {
                // add days value
                if (diff.Days > 1)
                    loggedTime = diff.Days.ToString() + " days";
                // add day
                else
                    loggedTime = diff.Days.ToString() + " day";

                // add comma if there's another value
                if (hours || minutes || seconds)
                    loggedTime = loggedTime + ", ";
            }
            if (hours)
            {
                // add "and" if there were days, and no minutes or seconds
                if (days && !(minutes || seconds))
                    loggedTime = loggedTime + "and ";

                // add hours value
                if (diff.Hours > 1)
                    loggedTime = loggedTime + diff.Hours.ToString() + " hours";
                // add hour
                else
                    loggedTime = loggedTime + diff.Hours.ToString() + " hour";

                // add comma if there's another value
                if (minutes || seconds)
                    loggedTime = loggedTime + ", ";
            }
            if (minutes)
            {
                // add "and" if there were days or hours, and no seconds
                if ((days || hours) && !seconds)
                    loggedTime = loggedTime + "and ";

                // add minutes value
                if (diff.Minutes > 1)
                    loggedTime = loggedTime + diff.Minutes.ToString() + " minutes";
                // add minute
                else
                    loggedTime = loggedTime + diff.Minutes.ToString() + " minute";

                // add comma if there's a seconds value
                if (seconds)
                    loggedTime = loggedTime + ", ";
            }
            if (seconds)
            {
                // add "and" if there was a previous value
                if (days || hours || minutes)
                    loggedTime = loggedTime + "and ";

                // add seconds value
                if (diff.Seconds > 1)
                    loggedTime = loggedTime + diff.Seconds.ToString() + " seconds";
                // add second
                else
                    loggedTime = loggedTime + diff.Seconds.ToString() + " second";
            }

            // just in case a user managed to get no time logged
            if (!(days || hours || minutes || seconds))
                loggedTime = "no time";

            // return string
            return loggedTime;
        }

        private long Base36Decode(string inputString)
        { // this method is based on the code found at https://en.wikipedia.org/wiki/Base_36#C.23_implementation (on 12/16/14)
            // vars
            string Clist = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            long result = 0;
            int pow = 0;

            // convert input string to upper-case
            inputString = inputString.ToUpper();

            // go through each char in input string
            for (int i = inputString.Length - 1; i >= 0; i--)
            {
                // find position value
                int pos = Clist.IndexOf(inputString[i]);

                // make sure it's a valid base-36 char
                if (pos > -1)
                    // raise position value to place value
                    result += pos * (long)Math.Pow(Clist.Length, pow);
                else
                    // report invalid value
                    return -1;

                // procede to the next place value
                pow++;
            }

            // return the equivalent base-10 number
            return result;
        }

        #endregion

        #region ToolStrip Menu Items

        private void ToolStripMenuItemExit_Click(object sender, EventArgs e)
        {
            // close this app
            this.Close();
        }

        private void ToolStripMenuItemNewCard_Click(object sender, EventArgs e)
        {
            // change status
            LabelStatus.Text = "Waiting for new card to be added . . .";

            // show form
            FormAddCard addCardForm = new FormAddCard();
            addCardForm.ShowDialog();

            // reload list of cards
            LoadCards();

            // reset status
            ResetStatus();
        }

        private void ToolStripMenuItemEdit_Click(object sender, EventArgs e)
        {
            // change status
            LabelStatus.Text = "Waiting for card editing to finish . . .";

            // show form
            FormEditCard editCardForm = new FormEditCard();
            editCardForm.ShowDialog();

            // reload list of cards
            LoadCards();

            // reset status
            ResetStatus();
        }

        private void ToolStripMenuItemRemoveCard_Click(object sender, EventArgs e)
        {
            // update status
            LabelStatus.Text = "Waiting for card removal to complete . . .";

            // show form
            FormRemoveCard removeCardForm = new FormRemoveCard();
            removeCardForm.ShowDialog();

            // reload list of cards
            LoadCards();

            // reset status
            ResetStatus();
        }

        private void TimeSheetToolStripMenuItemGenerate_Click(object sender, EventArgs e)
        {
            // update status
            LabelStatus.Text = "Waiting for time sheet to be generated . . .";

            // show form
            FormGenerate generateForm = new FormGenerate();
            generateForm.ShowDialog();

            // reset status
            ResetStatus();
        }

        private void ToolStripMenuItemAbout_Click(object sender, EventArgs e)
        {
            // update status
            LabelStatus.Text = "Waiting for About window to close . . .";

            // show about box
            FormAboutBox aboutBox = new FormAboutBox();
            aboutBox.ShowDialog();

            // reset status
            ResetStatus();
        }

        private void ToolStripMenuItemEditPast_Click(object sender, EventArgs e)
        {
            // update status
            LabelStatus.Text = "Waiting for past time editor to close . . .";

            // show form
            FormEditPast editForm = new FormEditPast();
            editForm.ShowDialog();

            // reset status
            ResetStatus();
        }

        private void ToolStripMenuItemAddTime_Click(object sender, EventArgs e)
        {
            // update status
            LabelStatus.Text = "Waiting for additional time to be added . . .";

            // show form
            FormAddTime addForm = new FormAddTime();
            addForm.ShowDialog();

            // reset status
            ResetStatus();
        }

        #endregion


        private void clockTimer_Tick(object sender, EventArgs e)
        {
            Clock.Text = DateTime.Now.ToString("hh:mm:ss tt");
            dateBox.Text = DateTime.Now.ToString("D");
        }

        //http://stackoverflow.com/questions/11952075/timer-refresh-functionality-for-text-box
    }

    class Card
    {
        public string cardID { set; get; }
        public string fName { set; get; }
        public bool clockedIn { set; get; }

        public Card(string id, string firstName, bool isClockedIn)
        {
            this.cardID = id;
            this.fName = firstName;
            this.clockedIn = isClockedIn;
        }
    }
}